import pygame as p


G_WIDTH = 1300
G_HEIGHT = 750

WIDTH = I_WIDTH = G_WIDTH - 300
HEIGHT = 2 * G_HEIGHT // 3
I_HEIGHT = G_HEIGHT//3


INCREMENT = 50

V_SHIFT = 0
H_SHIFT_INIT = 0
H_SHIFT = H_SHIFT_INIT
AMPLITUDE = 1
FREQUENCY = 1

MAX_FPS = 60


COS_AMPLITUDE = 1
COS_FREQUENCY = 1
COS_V_SHIFT = 0
COS_H_SHIFT_INIT = 0
COS_H_SHIFT = COS_H_SHIFT_INIT

TAN_AMPLITUDE = 1
TAN_FREQUENCY = 1
TAN_V_SHIFT = 0
TAN_H_SHIFT_INIT = 0
TAN_H_SHIFT = TAN_H_SHIFT_INIT

DEGREE = 0

SIN_COLOR = p.Color("#4a525a")
SIN_COLOR_ON = p.Color('#818c98')
COS_COLOR = p.Color("#24272b")
COS_COLOR_ON = p.Color("#828b97")
TAN_COLOR = p.Color("#07070a")
TAN_COLOR_ON = p.Color("#828b97")

SHIFT_SPEED = FREQUENCY/15
COS_SPEED = COS_FREQUENCY/15
TAN_SPEED = TAN_FREQUENCY/15